#include<iostream>
using namespace std;
int main(){
    vector<int>v;
    v.push_back(8);
    v.push_back(5);
    v.push_back(3);
    v.push_back(4);
    v.push_back(2);
    v.push_back(9);
    v.push_back(8);
    v.push_back(5);
    v.push_back(3);
    v.push_back(4);
    v.push_back(2);
    v.push_back(9);
    v.push_back(8);
    v.push_back(5);
    v.push_back(3);
    v.push_back(4);
    v.push_back(2);
    v.push_back(9);
    cout<<"size is : "<<v.size()<<endl;
    cout<<"capacity is : "<<v.capacity()<<endl;
    v.pop_back();
    v.pop_back();
    v.pop_back();
    v.pop_back();
    v.pop_back();
    v.pop_back();
    v.pop_back();
    v.pop_back();
    v.pop_back();
    v.pop_back();
    v.pop_back();
    v.pop_back();
    v.pop_back();
    v.pop_back();
    cout<<"size is : "<<v.size()<<endl;
    cout<<"capacity is : "<<v.capacity()<<endl;
}    